language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

sudo: false

before_install: bash travis/install_phan.sh

install: travis_retry composer install

script:
  - composer ci
  - bash travis/run_phan.sh

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikidata-feed"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"

cache:
  directories:
    - $HOME/.composer/cache
